//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chambre
    {
        public int IdChambre { get; set; }
        public string NumChambre { get; set; }
        public string ImageChambre { get; set; }
        public decimal PrixChambre { get; set; }
        public int BookingStatusId { get; set; }
        public int idTypeChambre { get; set; }
        public int CapaciteChambre { get; set; }
        public string DescriptionChambre { get; set; }
        public bool IsActive { get; set; }
    }
}
